### ISSUE TITLE
Error : unable to run 

### ISSUE THREAD

**Issue by r0hi7** [zeroharbor/detux-api#4]
`
AttributeError: 'Detux' object has no attribute 'logger'
`

**Comment by deadbits** [comment]
Sorry I'm only just now seeing this issue. I'll look into this over the weekend and patch it. I'm sure it's a very simple error somewhere.

Thanks for adding this @r0hi7

**Comment by deadbits** [comment]
This should be taken care of by commit https://github.com/zeroharbor/detux-api/commit/0280f2d21da66480d94435d9d5e0e6a83b308179

Granted I patched it from my phone on the go, and this library needs a bit of work all around but this should at least fix the logging issue

**Comment by deadbits** [comment]
Closing . fixed per above commit
